baseURL = 'https://goldengatesoftwaresolutions.com/'
languageCode = 'en-us'
title = 'Golden Gate Software Solutions'

[params]
  description = 'Software development company based in San Francisco, CA.'

[menu]
  [[menu.main]]
    name = 'Services'
    pageRef = '/services'
    weight = 10
  [[menu.main]]
    name = 'Portfolio'
    pageRef = '/portfolio'
    weight = 20
  [[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 30
  [[menu.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 40

[module]
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "node_modules"
    target = "assets/node_modules"
  [[module.mounts]]
    source = "static"
    target = "static"
